### ISSUE TITLE
Module doesn't look for errors when doing snmpwalk

### ISSUE THREAD

**Issue by losgrandes** [jhthorsen/snmp-effective#4]
Module stops walking only when it gets Timeout, that's ok, but I've discovered that it endlessly polls target when receiving 'noAccess' snmp response.
Example:
In Cisco Nexus 3064 you can tie port to $vlan without creating $vlan in config. Then when polling for dot1dTpFdbEntry OID on Community public@$vlan in order to get neighbor info, it'll receive 'noAccess' error.

I think this and other errors too should be handled in _walk.

**Comment by losgrandes** [comment]
https://github.com/jhthorsen/snmp-effective/pull/5

**Comment by jhthorsen** [comment]
This is pretty bad, but unfortunately the PR cannot be accepted.

**Comment by jhthorsen** [comment]
I'm going to close this, since it's old.
